// Root Layout for global components //

//Imports
import type { Metadata } from "next";
import "./globals.css";
import { exo2, orbitron } from "./fonts"

//Global components
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

//Set metadata
export const metadata: Metadata = {
  title: "Next.js Template | Landing",
  description: "Generated by create next app",
};

//Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${orbitron.variable} ${exo2.variable}`}>
      <body className={`${exo2.className} pb-48`}>
      {/* <body className="font-sans"> */}
        {/* Insert global nav bar component */}
        <Navbar />

        {/* Insert pages */}
        {children}

      </body>
      <Footer/>
    </html>
  );
}
