// Root Layout for global components //

//Imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//Global components
import Navbar from "./components/Navbar";

//Font
const inter = Inter({ subsets: ["latin"] });

//Set metadata
export const metadata: Metadata = {
  title: "Next.js Template | Landing",
  description: "Generated by create next app",
};

//Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Insert global nav bar component */}
        <Navbar />

        {/* Insert pages */}
        {children}

      </body>
    </html>
  );
}
